[2025-07-12T00:00:24.864+0000] {processor.py:157} INFO - Started process (PID=6870) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:24.869+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:00:24.873+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:24.871+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:25.030+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:25.007+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:00:25.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:25.181+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.348 seconds
[2025-07-12T00:00:55.338+0000] {processor.py:157} INFO - Started process (PID=6882) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:55.340+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:00:55.343+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:55.342+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:55.368+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:55.364+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:00:55.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:00:55.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.086 seconds
[2025-07-12T00:01:25.726+0000] {processor.py:157} INFO - Started process (PID=6892) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:25.729+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:01:25.730+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:25.730+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:25.759+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:25.749+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:01:25.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:25.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.082 seconds
[2025-07-12T00:01:56.570+0000] {processor.py:157} INFO - Started process (PID=6902) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:56.573+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:01:56.574+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:56.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:56.592+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:56.589+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:01:56.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:01:56.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.091 seconds
[2025-07-12T00:02:27.819+0000] {processor.py:157} INFO - Started process (PID=6912) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:27.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:02:27.825+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:27.824+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:27.926+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:27.893+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:02:27.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:27.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.165 seconds
[2025-07-12T00:02:58.533+0000] {processor.py:157} INFO - Started process (PID=6922) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:58.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:02:58.536+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:58.535+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:58.554+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:58.550+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:02:58.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:02:58.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.069 seconds
[2025-07-12T00:03:28.955+0000] {processor.py:157} INFO - Started process (PID=6932) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:28.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:03:28.958+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:28.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:28.978+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:28.975+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:03:28.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:29.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.051 seconds
[2025-07-12T00:03:59.303+0000] {processor.py:157} INFO - Started process (PID=6942) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:59.305+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:03:59.307+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:59.306+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:59.323+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:59.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:03:59.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:03:59.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.051 seconds
[2025-07-12T00:04:29.718+0000] {processor.py:157} INFO - Started process (PID=6952) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:04:29.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:04:29.720+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:04:29.720+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:04:29.787+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:04:29.781+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:04:29.789+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:04:29.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.125 seconds
[2025-07-12T00:05:00.211+0000] {processor.py:157} INFO - Started process (PID=6962) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:05:00.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:05:00.214+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:05:00.213+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:05:00.228+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:05:00.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:05:00.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:05:00.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.060 seconds
[2025-07-12T00:06:20.059+0000] {processor.py:157} INFO - Started process (PID=6974) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:06:20.062+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:06:20.064+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:06:20.063+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:06:20.169+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:06:20.162+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:06:20.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:06:20.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.198 seconds
[2025-07-12T00:08:46.420+0000] {processor.py:157} INFO - Started process (PID=6984) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:08:46.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:08:46.435+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:08:46.433+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:08:46.850+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:08:46.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:08:46.856+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:08:47.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.689 seconds
[2025-07-12T00:09:17.375+0000] {processor.py:157} INFO - Started process (PID=6996) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:09:17.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:09:17.384+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:09:17.384+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:09:17.405+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:09:17.400+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:09:17.406+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:09:17.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.095 seconds
[2025-07-12T00:25:29.570+0000] {processor.py:157} INFO - Started process (PID=7008) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:25:29.573+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:25:29.576+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:25:29.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:25:29.607+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:25:29.602+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:25:29.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:25:29.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.100 seconds
[2025-07-12T00:31:12.364+0000] {processor.py:157} INFO - Started process (PID=7020) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:12.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:31:12.376+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:12.374+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:12.456+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:12.434+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:31:12.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:14.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 1.956 seconds
[2025-07-12T00:31:45.361+0000] {processor.py:157} INFO - Started process (PID=7030) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:45.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:31:45.367+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:45.366+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:45.428+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:45.415+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:31:45.429+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:31:45.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.259 seconds
[2025-07-12T00:32:15.969+0000] {processor.py:157} INFO - Started process (PID=7040) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:15.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:32:15.974+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:15.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:15.994+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:15.991+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:32:15.994+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:16.026+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.066 seconds
[2025-07-12T00:32:46.429+0000] {processor.py:157} INFO - Started process (PID=7050) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:46.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:32:46.441+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:46.439+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:46.492+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:46.486+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:32:46.494+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:32:46.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.133 seconds
[2025-07-12T00:33:17.085+0000] {processor.py:157} INFO - Started process (PID=7060) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:17.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:33:17.091+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:17.090+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:17.113+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:17.110+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:33:17.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:17.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.066 seconds
[2025-07-12T00:33:47.452+0000] {processor.py:157} INFO - Started process (PID=7070) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:47.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:33:47.456+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:47.455+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:47.474+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:47.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:33:47.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:33:47.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.059 seconds
[2025-07-12T00:34:17.920+0000] {processor.py:157} INFO - Started process (PID=7080) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:17.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:34:17.923+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:17.923+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:17.938+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:17.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:34:17.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:17.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.049 seconds
[2025-07-12T00:34:48.271+0000] {processor.py:157} INFO - Started process (PID=7090) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:48.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:34:48.274+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:48.274+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:48.294+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:48.291+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:34:48.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:34:48.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.066 seconds
[2025-07-12T00:35:18.638+0000] {processor.py:157} INFO - Started process (PID=7100) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:35:18.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:35:18.640+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:35:18.640+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:35:18.654+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:35:18.652+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:35:18.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:35:18.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.044 seconds
[2025-07-12T00:42:12.933+0000] {processor.py:157} INFO - Started process (PID=7112) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:13.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:42:13.272+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:13.256+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:14.020+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:13.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:42:14.037+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:14.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 2.606 seconds
[2025-07-12T00:42:45.201+0000] {processor.py:157} INFO - Started process (PID=7122) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:45.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:42:45.209+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:45.207+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:45.240+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:45.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:42:45.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:42:45.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.130 seconds
[2025-07-12T00:43:16.107+0000] {processor.py:157} INFO - Started process (PID=7132) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:16.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:43:16.135+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:16.134+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:16.207+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:16.193+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:43:16.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:16.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.299 seconds
[2025-07-12T00:43:46.873+0000] {processor.py:157} INFO - Started process (PID=7142) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:46.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:43:46.882+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:46.881+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:46.937+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:46.929+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:43:46.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:43:47.009+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.221 seconds
[2025-07-12T00:44:17.945+0000] {processor.py:157} INFO - Started process (PID=7152) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:17.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:44:17.951+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:17.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:17.974+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:17.971+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:44:17.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:18.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.077 seconds
[2025-07-12T00:44:48.834+0000] {processor.py:157} INFO - Started process (PID=7162) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:48.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:44:48.838+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:48.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:48.858+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:48.854+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:44:48.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:44:48.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.084 seconds
[2025-07-12T00:45:19.580+0000] {processor.py:157} INFO - Started process (PID=7172) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:19.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:45:19.586+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:19.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:19.625+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:19.620+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:45:19.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:19.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.138 seconds
[2025-07-12T00:45:50.258+0000] {processor.py:157} INFO - Started process (PID=7182) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:50.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:45:50.264+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:50.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:50.284+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:50.280+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:45:50.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:45:50.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.126 seconds
[2025-07-12T00:46:21.076+0000] {processor.py:157} INFO - Started process (PID=7192) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:21.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:46:21.080+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:21.079+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:21.103+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:21.100+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:46:21.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:21.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.096 seconds
[2025-07-12T00:46:51.587+0000] {processor.py:157} INFO - Started process (PID=7202) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:51.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:46:51.596+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:51.595+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:51.622+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:51.619+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:46:51.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:46:51.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.119 seconds
[2025-07-12T00:47:22.801+0000] {processor.py:157} INFO - Started process (PID=7212) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:22.806+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:47:22.819+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:22.814+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:22.892+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:22.870+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 5, in <module>
    from src.models.trainer import ModelTrainer
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:47:22.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:23.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.550 seconds
[2025-07-12T00:47:48.050+0000] {processor.py:157} INFO - Started process (PID=7225) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:48.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:47:48.058+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:48.057+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:48.552+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:48.523+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:47:48.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:47:48.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.795 seconds
[2025-07-12T00:48:19.592+0000] {processor.py:157} INFO - Started process (PID=7237) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:19.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:48:19.602+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:19.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:19.822+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:19.808+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:48:19.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:19.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.283 seconds
[2025-07-12T00:48:50.125+0000] {processor.py:157} INFO - Started process (PID=7247) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:50.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:48:50.128+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:50.128+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:50.168+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:50.163+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:48:50.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:48:50.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.072 seconds
[2025-07-12T00:49:21.170+0000] {processor.py:157} INFO - Started process (PID=7257) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:21.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:49:21.173+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:21.172+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:21.244+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:21.232+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:49:21.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:21.291+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.128 seconds
[2025-07-12T00:49:52.010+0000] {processor.py:157} INFO - Started process (PID=7267) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:52.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:49:52.023+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:52.022+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:52.301+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:52.288+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:49:52.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:49:52.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.352 seconds
[2025-07-12T00:50:22.504+0000] {processor.py:157} INFO - Started process (PID=7277) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:22.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:50:22.507+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:22.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:22.541+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:22.537+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:50:22.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:22.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.061 seconds
[2025-07-12T00:50:53.094+0000] {processor.py:157} INFO - Started process (PID=7282) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:53.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:50:53.100+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:53.099+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:53.152+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:53.141+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:50:53.153+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:50:53.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.126 seconds
[2025-07-12T00:51:23.976+0000] {processor.py:157} INFO - Started process (PID=7292) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:23.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:51:23.982+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:23.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:24.047+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:24.035+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:51:24.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:24.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.168 seconds
[2025-07-12T00:51:54.360+0000] {processor.py:157} INFO - Started process (PID=7302) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:54.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:51:54.366+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:54.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:54.396+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:54.392+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:51:54.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:51:54.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.077 seconds
[2025-07-12T00:52:25.141+0000] {processor.py:157} INFO - Started process (PID=7312) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:25.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:52:25.149+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:25.148+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:25.227+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:25.216+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:52:25.231+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:25.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.174 seconds
[2025-07-12T00:52:55.573+0000] {processor.py:157} INFO - Started process (PID=7322) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:55.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:52:55.577+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:55.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:55.634+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:55.627+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:52:55.635+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:52:55.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.123 seconds
[2025-07-12T00:53:26.009+0000] {processor.py:157} INFO - Started process (PID=7332) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:26.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:53:26.014+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:26.014+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:26.090+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:26.081+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:53:26.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:26.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.150 seconds
[2025-07-12T00:53:57.125+0000] {processor.py:157} INFO - Started process (PID=7342) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:57.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:53:57.133+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:57.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:57.194+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:57.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:53:57.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:53:57.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.135 seconds
[2025-07-12T00:54:27.836+0000] {processor.py:157} INFO - Started process (PID=7352) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:27.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:54:27.843+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:27.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:27.913+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:27.906+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:54:27.914+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:27.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.167 seconds
[2025-07-12T00:54:58.375+0000] {processor.py:157} INFO - Started process (PID=7362) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:58.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:54:58.378+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:58.378+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:58.427+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:58.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:54:58.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:54:58.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.109 seconds
[2025-07-12T00:55:28.829+0000] {processor.py:157} INFO - Started process (PID=7372) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:28.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:55:28.835+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:28.834+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:28.922+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:28.911+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:55:28.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:28.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.159 seconds
[2025-07-12T00:55:59.544+0000] {processor.py:157} INFO - Started process (PID=7382) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:59.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:55:59.547+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:59.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:59.578+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:59.574+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:55:59.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:55:59.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.068 seconds
[2025-07-12T00:56:30.318+0000] {processor.py:157} INFO - Started process (PID=7392) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:56:30.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:56:30.324+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:56:30.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:56:30.458+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:56:30.449+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:56:30.459+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:56:30.529+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.222 seconds
[2025-07-12T00:57:00.892+0000] {processor.py:157} INFO - Started process (PID=7402) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:00.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:57:00.896+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:00.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:00.968+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:00.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:57:00.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:01.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.169 seconds
[2025-07-12T00:57:32.018+0000] {processor.py:157} INFO - Started process (PID=7412) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:32.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:57:32.022+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:32.021+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:32.076+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:32.068+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:57:32.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:57:32.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.116 seconds
[2025-07-12T00:58:02.276+0000] {processor.py:157} INFO - Started process (PID=7422) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:02.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:58:02.285+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:02.283+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:02.318+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:02.314+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:58:02.319+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:02.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.094 seconds
[2025-07-12T00:58:32.975+0000] {processor.py:157} INFO - Started process (PID=7432) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:32.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:58:32.981+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:32.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:33.015+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:33.011+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:58:33.015+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:58:33.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.096 seconds
[2025-07-12T00:59:03.887+0000] {processor.py:157} INFO - Started process (PID=7442) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:03.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:59:03.892+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:03.891+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:03.944+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:03.935+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:59:03.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:04.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.176 seconds
[2025-07-12T00:59:34.734+0000] {processor.py:157} INFO - Started process (PID=7452) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:34.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T00:59:34.739+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:34.739+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:34.800+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:34.794+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T00:59:34.802+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T00:59:34.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.146 seconds
[2025-07-12T01:00:06.084+0000] {processor.py:157} INFO - Started process (PID=7462) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:06.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T01:00:06.105+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:06.099+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:06.242+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:06.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T01:00:06.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:06.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.248 seconds
[2025-07-12T01:00:37.772+0000] {processor.py:157} INFO - Started process (PID=7472) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:37.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T01:00:37.779+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:37.778+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:37.930+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:37.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T01:00:37.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:00:38.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.330 seconds
[2025-07-12T01:01:09.001+0000] {processor.py:157} INFO - Started process (PID=7482) to work on /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:01:09.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_pipeline.py for tasks to queue
[2025-07-12T01:01:09.005+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:01:09.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:01:09.058+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:01:09.041+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_pipeline.py", line 11, in <module>
    from src.models.trainer import ModelTrainer
  File "/opt/airflow/src/models/trainer.py", line 1, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T01:01:09.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_pipeline.py
[2025-07-12T01:01:09.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_pipeline.py took 0.150 seconds
